apiVersion: v1
kind: Service
metadata:
  name: python01-max-dev
  labels:
    app: python01-back
spec:
  type: ClusterIP
  selector:
    app: python01-back
  ports:
  - port: 8800
    targetPort: 8800
